### ISSUE TITLE
No mention of file name in Module and Imports section in part 2

### ISSUE THREAD

**Issue by jpierson** [Elm-Detroit/elm-workshop#6]
Maybe I'm missing it but it looks like discussion starts with a specific file but I don't see where the specific source file is mentioned. Also note that if a mention is added such as Main.elm that it can link into the file using a markdown link.

https://github.com/Elm-Detroit/elm-workshop/blame/master/part2/README.md#L12

**Comment by mikeonslow** [comment]
Thanks @jpierson. It's funny that you mention it because it came up in both of my test runs yesterday and I had to say out loud that the person should open `Main.elm`. I'm going to update part2 - part9 with this info  at the top of each page shortly.

**Comment by jpierson** [comment]
I have a branch where I've added the details. Feel free to merge it.

https://github.com/Elm-Detroit/elm-workshop/tree/feature/issue-6-part-2-add-file-name

**Comment by mikeonslow** [comment]
Added these to then initial instruction at the top of each part. Will look into styling these so that they are a bit more visible.
