### ISSUE TITLE
Add elm-stuff to .gitignore

### ISSUE THREAD

**Issue by jpierson** [Elm-Detroit/elm-workshop#7]
Git is telling me that "stuff" under `elm-stuff` needs to be added.

![image](https://user-images.githubusercontent.com/1467146/32323600-f428d656-bf9e-11e7-8675-10c9a50520be.png)

We should add elm-stuff to the .gitignore. I believe there is a standard .gitignore that I pulled for Elm projects somewhere that we could probably use.

**Comment by mikeonslow** [comment]
I originally had it in there (used the elm .gitignore template you mentioned) but I decided to remove it from the ignore list so that folks don't need to re-run `elm package install` every time we switch to the next part.

**Comment by jpierson** [comment]
I see, are things in elm-stuff portable between platforms. From what I recall it's just Elm code unlike some other package ecosystems for other languages so it should be fine. I'm trying to recall if there is a way in git to include files that are not able to be modified... I want to say that there was but I can't recall off the top of my head.

**Comment by mikeonslow** [comment]
I do believe it's portable, it's .elm, .elmi etc.

**Comment by mikeonslow** [comment]
@jpierson just a heads up: as noted I'm going to remove elm-stuff and then add it to .gitignore. 

To simplify things, I'm also going to create a small npm script that both runs `elm package install --yes` and `elm-live Main.elm --output=static/js/elm.js --pushstate --open`

**Comment by mikeonslow** [comment]
@jpierson Just saw your PR, you rock man!

**Comment by mikeonslow** [comment]
npm script to added in part2 - part9. We still need to update the documentation to reflect this change. We can now run `npm start` in these directories to both install elm packages and run elm-live with the proper arguments
